version: '3.8'

services:
  neo4j:
    image: neo4j:5.16.0
    container_name: neo4j_container
    environment:
      - NEO4J_AUTH=neo4j/password  # Username: neo4j, Password: password
    ports:
      - "7687:7687"  # Bolt connection for Neo4j
      - "7474:7474"  # Web UI for Neo4j
    volumes:
      - neo4j_data:/data
      - neo4j_logs:/logs

  fastapi:
    build: .
    container_name: fastapi_container
    environment:
      - NEO4J_URI=bolt://neo4j:7687
      - NEO4J_USER=neo4j
      - NEO4J_PASSWORD=password
      - OPENAI_API_KEY=your-openai-api-key
    depends_on:
      - neo4j
    ports:
      - "8000:8000"

volumes:
  neo4j_data:
  neo4j_logs:
